### ISSUE TITLE
Unexpected crash

### ISSUE THREAD

**Issue by wboeke** [tdwsl/aster-forth#8]
Hello,
Sometimes aster will compile a valid forth program with no problems, but crash at runtime.
I attached an example of this (from Rosetta, somewhat modified) hereunder. It runs correctly with pforth and gforth.

I found the exact location of the crash, it's in the word 'scan'. An outcommented version of this word is included, it will exit at the 'bye', but no output of course.

If you have some time to spare, could you look at this? You implemented all looping words in forth, using the return-stack a lot. Maybe this does'nt work always?

[roman-dec2.f.txt](https://github.com/tdwsl/aster-forth/files/13473278/roman-dec2.f.txt)

**Comment by tdwsl** [comment]
Hey, sorry about that. I didn't notice it before, but while .. repeat didn't work with multiple whiles, something I hadn't considered previously. Anyway, I fixed it now, and you're right about the return stack; I already used a separate stack when I was implementing case, and I'm now doing the same for begin loops.
Thanks for letting me know!

**Comment by wboeke** [comment]
Sorry to reopen, but the new patch did not solve the problem. Please run the roman-dec2.f program without the 'bye' word in the code of 'scan', and look what happens. The result should be: 1954

**Comment by tdwsl** [comment]
That's right, I can run it and get 1954. In the code you sent, the line with 'bye' was commented out. Are you sure that you're running the latest version?

**Comment by wboeke** [comment]
Yes!
Tomorrow I am going to test it on another computer.
P.S. I did, fresh install, compile, run example, all okay! Please forget this post.

**Comment by tdwsl** [comment]
Glad to hear it!
